### ISSUE TITLE
SEND bad math or hidden operations: fee, max, totals

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#103]
Multiple issues with math: 
automatic/custom fee from SEND window differs with explorer.testnet.veladev.net report.
after sending with "use max" and auto fee - still 0,002 remains on the senders account.
after trying to send all remains (zeroing account) something left anyway.

Prerequisites:
Testnet, VLX

Steps to reproduce:
1. Top up a new account from Telegram bot.
2. Click 'Send' from the account.
3. Use yet another new account address in 'to' field.
4. Click "use max" > SEND.
5. Click the Transaction Details link.
6. Check sender's and receiver's explorer.testnet.veladev.net balances clicking respective links.

7. **Pay attention:** fee from SEND window was  0,000000022; 
    fee from explorer.testnet   0.000000000462 TX Fee; balance left on Sender's account.

8. Copy sender's balance from explorer.testnet
9. Again - use same accounts in SEND window
10. Click 'custom' radio button transaction fee (live same as auto was - 0,000000022)
11. 'Amount': input sender's full balance minus fee
12. Repeat steps 5, 6, 7.

Expected result: good math, clear reports :)
 
Actual result: looks like guys are messing with rounding,
probably combined with intermediate operations (dollar ?)

![bad math 2](https://user-images.githubusercontent.com/73913130/106761557-9e4fcc00-663d-11eb-97d3-5f2a64eec3ab.jpg)
![bad math 1](https://user-images.githubusercontent.com/73913130/106761568-a14abc80-663d-11eb-92ea-76034b8d77de.jpg)
![bad math 3](https://user-images.githubusercontent.com/73913130/106761798-da832c80-663d-11eb-86b2-f2744e39a7bf.jpg)

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by Corresponsible** [comment]
Use max gives a 'buffer' because auto fee can fluctuate, so if it gets higher moments before transaction, you will end up with 'not enough funds' error.
As per wrong fee: there are some unnecesary steps, could you please refactor as in https://github.com/velas/JsWallet/issues/50

**Comment by DmRos** [comment]
How about - "after trying to send all remains (zeroing account) something left anyway. " ?

Click 'custom' radio button transaction fee (live same as auto was - 0,000000022)

'Amount': input sender's full balance minus fee

Repeat steps 5, 6, 7.


as per different fees - I will put in new issue

**Comment by Corresponsible** [comment]
if the fee from send window is bigger than actual fee, the difference would stay on balance, so that also goes to "incorrect fee" bug
