### ISSUE TITLE
In Mainnet BTC and LTC wallet don`t match, but on Testnet they match

### ISSUE THREAD

**Issue by Anthrax941** [velas/JsWallet#104]
**Screenshot**
![Безымянный](https://user-images.githubusercontent.com/73966415/106765397-6f3b5980-6641-11eb-921a-72401e3fad42.png)
![Безымянный2](https://user-images.githubusercontent.com/73966415/106765402-706c8680-6641-11eb-8dd3-142f87d93407.png)

**Steps to reproduce:**
1. Go to 'Settings'
2. Click on toggle 'Test network'

**Expected result**
wallet BTC and LTC don`t match

**Actual result**
wallet BTC and LTC match up

**Environment:**
- Build [0.13.21]
- OS [Windows 10]
- Browser [Chrome]
- Version [88.0.4324.146]

**Comment by Corresponsible** [comment]
BTC and LTC testnet addresses are the same, not a bug
