### ISSUE TITLE
Fee from SEND window/transactions list differs from explorer.testnet transactions report

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#105]
Automatic or custom fee from SEND window (same later displayed in accounts transactions list) differs with explorer.testnet.veladev.net reports.

Prerequisites:
Testnet, VLX

Steps to reproduce:
1.	Go to wallets,
2.	Click send
3.	Input a valid account address into ‘To’ field
4.	Click 'custom' radio button transaction fee (live same as auto was - 0,000000022)
5.	Click 'send', confirm
6.	Click the Transaction Details link.

Pay attention: fee from SEND window was 0,000000022; fee from explorer.testnet 0.000000000462 TX Fee; 

Expected result: fee from SEND window and  fee from explorer.testnet reports are same

Actual result: fee from SEND window and account transactions list (0,000000022) on wallet.velas.com differs from explorer.testnet.veladev.net transactions report (0.000000000462 TX - always!).

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by rodinant** [comment]
Please note: after pressing the SEND button, the fee of the last transaction is displayed correctly. But the previous one is already wrong.
![transaction in progress](https://user-images.githubusercontent.com/73893397/106806590-d3294680-6670-11eb-803c-2e38d295017a.jpg)
