### ISSUE TITLE
When pressing 'use max' in the USDT_ERC20 wallet send window results in an error

### ISSUE THREAD

**Issue by Anthrax941** [velas/JsWallet#106]
**Summary**
If in the window 'Send' wallet 'USDT_ERC20' push the button 'use max' a confirmation window appears with an error message "TypeError: Cannot read property 'cheap' of undefined"

**Screenshot**
![Безымянный2](https://user-images.githubusercontent.com/73966415/106784712-5177ef80-6655-11eb-9327-b123d15cbb09.png)

**Steps to reproduce:**
1. Go to 'USDT_ERC20'
2. Go to 'Send'
3. Сlick 'use max'

**Expected result**
The "use max" button does not ask for confirmation of action.

**Actual result**
A confirmation window appears with an error message "TypeError: Cannot read property 'cheap' of undefined"

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.146]

**Comment by Corresponsible** [comment]
2 things in one report, I suggest you erase "icon shifted" part
