### ISSUE TITLE
Over time, it does not go to the login screen automatically if the site is not open on the WALLETS page

### ISSUE THREAD

**Issue by rodinant** [velas/JsWallet#107]
**Summary**
Over time, it does not go to the login screen automatically if the site is not open on WALLETS page

**Steps to reproduce:**
1. Log in to the site.
2. Go to any page other than WALLETS and do not be active

**Expected result**
After about 2 minutes, the site should go to the login page

**Actual result**
Site remains open

**Environment:**
• Testnet or Mainnet
• Build [0.13.21]
• OS [Windows 7 x64]
• Browser [Chrome]
• Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
dup https://github.com/velas/JsWallet/issues/14#issue-792005974
