### ISSUE TITLE
If only 2 wallets are visible, then both are shown as active

### ISSUE THREAD

**Issue by rodinant** [velas/JsWallet#108]
**Summary**
If only 2 wallets are visible, then both are shown as active. 
**Screenshot**
![as active](https://user-images.githubusercontent.com/73893397/106873802-816ad580-66dd-11eb-9045-54bc101892ba.jpg)

**Steps to reproduce:**
1. Go to WALLETS
2. If only 2 wallets are visible, then both are shown as active.

**Expected result**
One selected wallet is shown as active

**Actual result**
Both wallets as active

**Additional Screenshots and/or Videos**
https://user-images.githubusercontent.com/73893397/106874675-87ad8180-66de-11eb-833e-e662320c16a5.mov

**Environment:**
• Testnet or Mainnet
• Build [0.13.21]
• OS [Windows 7 x64]
• Browser [Chrome]
• Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
1 both active is a bug 
2 not all wallets support testnet, they shouldn't be in testnet list, but that's of for now
