### ISSUE TITLE
Same address for LTC and BTC for an account in Testnet

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#109]
Prerequisites:
Testnet

Steps to reproduce:

1. Wallets > add BTC and  LTC  if not done before
2. Select and copy and paste in a text file addresses for the coins, compare.

Pay attention: same Velas account for all steps; this issue does not apply to Mainnet.

Expected result: all different coins get different addresses for accounts

Actual result: same address for LTC and BTC for an account in Testnet

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by DmRos** [comment]
hi, how people convert coins in testnet? can't find way. want to test.
or have to have real coins in mainnet?

**Comment by Corresponsible** [comment]
https://t.me/velas_faucet_bot for VLX coins, services for other test coins can be found at google.com

as per your issue, see https://github.com/velas/JsWallet/issues/104#issue-800417574
it's not a bug

Testnet is mainly there to test something instead mainnet, so you don't spend actual money. It is often that the bug will reproduce in mainnet, so better do file testnet bugs.

**Comment by DmRos** [comment]
anyway, people convert and test other coins in testnet. How to have other tokens?
