### ISSUE TITLE
Not able add listed wallets for some coins/tokens in Testnet

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#110]
Prerequisites:
Testnet

Steps to reproduce:

1. Wallets > click button (right of search field) to add coins
2. Click  '+'  icons one by one for all coins

Pay attention: only btc, ltc, eth are visible, wallets for other coins not in both (for adding and added) lists; this issue does not apply to Mainnet.

Expected result: able to add wallets for any (listed) coins/tokens

Actual result: only btc, ltc, eth are visible, other tokens are invisible.

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by Corresponsible** [comment]
https://github.com/velas/test-us/issues/10#issuecomment-773264658
