### ISSUE TITLE
‘min’  button inputs 10,000 in ‘stake more’ while there is no minimum for the transaction

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#112]
Prerequisites:
Testnet, an account, already staking in a pool

Steps to reproduce:
1.	Staking > chose a pool your account is staking already 
2.	stake more > press ‘min’
3.	Change to amount less than 10,000 (222) > apply > confirm

Pay attention:  pressing 'min' in Stake More will input 10000.

Expected result:  'min' should not be applicable or set to appropriate or no 'min' button with Stake More.
Actual result:  ‘min’  button inputs 10,000 in ‘stake more’

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by Corresponsible** [comment]
With stake more you can add any amount to already existing stake, min button and alert are the problem, refactor as per min button and alert
