### ISSUE TITLE
Wrong alert message after staking more while withdrawing or moving stake

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#114]
Prerequisites:
Testnet; 
an account, already staking in a pool;
same epoch during test.

Steps to reproduce:
1. Staking > chose the pool your account is staking already 
2. Stake more >  input any small amount (222) > apply > confirm
3. Repeat step 1 > withdraw or move stake > input more than in step 2 (333) or live default (your stake) > the message pops up
4. Click > 'x'  in the message
5. Withdraw or Move stake > input 222 or less > apply > confirm

Pay attention:  pressing 'min' in Stake More will input 10000, nothing actually moving in result of step 5, thou transaction will complete.

Expected result: right amount allowed for Withdraw and Move Stake if the transactions allowed, right message.
Actual result: Wrong alert message after staking more, faulty transaction

Aftereffect: Withdraw and move stake become possible for amount <= the invalid amount from step 1.  (222), strange sum in alert message pops up if input more.

![222 3](https://user-images.githubusercontent.com/73913130/106902938-0bc53080-6702-11eb-8b5e-432d915adeda.jpg)

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104

**Comment by Corresponsible** [comment]
Can you send video?

**Comment by DmRos** [comment]
its a bit different now. i see now there is no UI error on refreshing balance too.
and new alert for min stake during SECOND staking more but not first time...
and many zeroes without decimal point in report



Uploading bandica
m 2021-02-06 00-12-54-790.mp4…

there is other video hub not allows..

**Comment by DmRos** [comment]
something went wrong with previous message.
https://user-images.githubusercontent.com/73913130/107140254-86bc6000-6929-11eb-8551-df9511e78076.mp4
there is other video hub not allows..  https://drive.google.com/file/d/1YExl0qEyvyNIBu8MNV_VWhzyyl1CEyIJ/view?usp=sharing

also you can see prefilled numbers in move from previous testing operations still in cache
no more zeroes in alert message, but in transactions reports they are...

**Comment by DmRos** [comment]
Hi, something went wrong with previous message.

https://drive.google.com/file/d/1YExl0qEyvyNIBu8MNV_VWhzyyl1CEyIJ/view?usp=sharing
https://drive.google.com/file/d/1SuMTqg5-Pw8PemnefMFS9REGJ9MJoJbP/view?usp=sharing
also you can see prefilled numbers in Move Stake from previous testing operations still in cache
no more zeroes in alert message, but in transactions reports they are...

And I still want to know how can I get other coins/tokens in testnet. google knows about converting real coins only.

**Comment by Corresponsible** [comment]
For testnet coins google: BTC faucet\LTC faucet or ETH faucet - try some of the results to find a working one
