### ISSUE TITLE
Always the same message about the fee at the staking contract, but always different fee in practice

### ISSUE THREAD

**Issue by rodinant** [velas/JsWallet#115]
**Summary**
Always the same message about the fee when staking contract (0.000000022 VLX), but always always different on explorer.testnet.veladev.net and in the transaction history on the WELLAS page (depending on the case)

**Screenshot**
![Screenshot_1](https://user-images.githubusercontent.com/73893397/106928816-45a33080-671c-11eb-82aa-97c5536acfd3.jpg)
![rewards - claim](https://user-images.githubusercontent.com/73893397/106928988-7be0b000-671c-11eb-9a41-85e609bf9449.jpg)

**Steps to reproduce:**
1. Go to STAKING -> DELEGATE -> SELECT POOL
2. Press REWARDS - > CLAIM or EXIT -> WITHDRAW or STAKING - APPLY. Always the same message about the fee when staking contract (0.000000022 VLX)

**Expected result**
The fee must match in the message and on explorer.testnet.veladev.net and in the transaction history on the WELLAS page

**Actual result**
On explorer.testnet.veladev.net and in the transaction history on the WELLAS page: 
-  when REWARDS - > CLAIM fee is 0.000009008005
- when EXIT -> WITHDRAW and STAKING - APPLY fee is depends on the amount

**Environment:**
• Testnet
• Build [0.13.21]
• OS [Windows 7 x64]
• Browser [Chrome]
• Version [88.0.4324.104]

**Comment by rodinant** [comment]
Also go to SEARCH -> VOTE -> press VOTE: We can see the message "You are allowed to spend... (0.000000022 VLX)". But real fee is 0.000000068422.
![Screenshot_1](https://user-images.githubusercontent.com/73893397/106943022-8c4d5680-672d-11eb-9430-0bff5ac0576a.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/73893397/106943025-8d7e8380-672d-11eb-962a-2b95d58d83a8.jpg)

**Comment by DmRos** [comment]
looks like same with #105

**Comment by rodinant** [comment]
Yes, maybe it is possible to combine 2 issues into one.

**Comment by Corresponsible** [comment]
Should be amendment for https://github.com/velas/JsWallet/issues/105
