### ISSUE TITLE
There is a way to see all currencies in Testnet

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#116]
Steps to reproduce:

1. Testnet > Wallets > click button (right of search field) to add coins
2. Click '+' icons one by one for all coins

Pay attention: only btc, ltc, eth are visible, wallets for other coins not in both (for adding and added) lists

3. Mainnet > Wallets > click on any hidden in Testnet coin > switch to Testnet

Expected result: only btc, ltc, eth are visible, other tokens are invisible in Testnet ( https://github.com/velas/test-us/issues/10#issuecomment-773264658 )
Actual result:   able to add and see wallets for any (listed) coins/tokens in Testnet.

![image](https://user-images.githubusercontent.com/73913130/106947567-367bad00-6733-11eb-9df7-d37d409e3e6e.png)

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by DmRos** [comment]
how to convert vlx to other coins? or get them for testing?

**Comment by rodinant** [comment]
looks like same with #67

**Comment by DmRos** [comment]
yes. thanks. only wrong assumption in 67 title. IMHO
