### ISSUE TITLE
Balance of "USDT Omni" is ".." in wallets page after refreshing page

### ISSUE THREAD

**Issue by Corresponsible** [velas/JsWallet#23]
Reproducibility: Random

Steps to reproduce:

1. Go to 'Wallets' page
2. Refresh balance 5-10 times
3. Pay attention to the USDT Omni balance

Expected result: Balance of "USDT Omni" is "0.00" in wallets page after refreshing page
Actual result: Balance of "USDT Omni" is ".." in wallets page after refreshing page

**Comment by PrivetQA** [comment]
can be reproduce with other wallets
![image](https://user-images.githubusercontent.com/71498900/106614068-9592c380-6573-11eb-9b00-e16e965aa904.png)

**Comment by Corresponsible** [comment]
amendment filed
