### ISSUE TITLE
[feature request] 'editing' account name is closed after deleting all values

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#64]
**Summary**
[feature request] 'editing' account name is closed after deleting all values

**Steps to reproduce:**
1. Click on 'change name' button
2. Delete all values
3. Pay attention to 'editing' field

**Expected result**
'editing' account name field is opened after deleting all values. After pressing 'Enter' shows message 'Enter name'; or 'editing' account name field closed, name of account returned to previous name

**Actual result**
'editing' account name field is closed after deleting all values

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
not currently looking for feature requests, everything that doesn't disturb functionality is not in priority for now
