### ISSUE TITLE
VLX transaction status gets stuck on "created"  and do not perform  after much of time

### ISSUE THREAD

**Issue by ArnerPan** [velas/JsWallet#66]
Summary
Any VLX   self-to-self transaction which have  a manual transaction fee less than 0.000000011 gets stuck on "Сreated"

**Screenshot**
![beep](https://user-images.githubusercontent.com/77290340/106507290-e0f99300-64db-11eb-8be3-88e7c34bf09b.jpg)

**VIDEO**
[RECORD](https://youtu.be/4CmU_s2koHU)

**Steps to reproduce:**
1. Go to 'Wallets'
2. Choose Velas wallet
3. Click  "send"
4. Copy  VLX  address wallet "from:"
5. Past  VLX address to "To"
6. Set any amount  but less than on   balance
7. Choose Transaction Fee "Custom"
8. Set value of Transaction Fee less than  0.000000011 or just  0.000000000
9. Click "Send"

**Expected result**
Transacton should be completed

**Actual result**
Transaction  status stucks  on  "Created"  and don`t  updating

**Environment:**
Build [0.13.21]
Device [laptop y530]
OS [Windows 10 x64]
Browser [Chrome]
Version [88.0.4324.104]

**Comment by PrivetQA** [comment]
**UPD**
same problem after sending Ethereum, status infinitely 'Created' in transactions history
![image](https://user-images.githubusercontent.com/71498900/106621478-4781be00-657b-11eb-8caa-b862bd7a92c4.png)

**Comment by ArnerPan** [comment]
And seems like it hapoens with any operations with any wallet and recipient  if  set these  fee values

P. S. after  10-13 operations system  seems to be overflowed with that, so  it will unable to accept. any "0 fee"  transaction until  do not be completed  transaction with fee greater than auto value, then it continues to stack "0 fee"  transactions.

**Comment by Corresponsible** [comment]
Ctypto transactions allow custom fee, the higher fee, the bigger chance to fet your transaction faster, as looks more worthy to validators, 0 or too small fee devalues priority, hence waiting time close to never being processed
