### ISSUE TITLE
Wallets from mainnet displayed after changing network to testnet

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#67]
**Summary**
Wallets from mainnet displayed after changing network to testnet

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106490766-d54ba380-64be-11eb-89a0-d213566863f5.png)

**Video**
https://youtu.be/4DatUN2bsog

**Steps to reproduce:**
1. Click on 'USDT Omni'(or Symblox, Symblox v2, Litecoin ) token
2. Click on [SEND]
3. Click on [CANCEL]
4. Go to 'Settings'
5. Change network to 'testnet'
6. Go to 'Wallets'
3. Pay attention to wallets

**Expected result**
Wallets from testnet is displayed

**Actual result**
Wallets from mainnet displayed after changing network to testnet

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by PrivetQA** [comment]
**Optimized steps to reproduce:**
1. Click on 'USDT Omni'(or Symblox, Symblox v2, Litecoin ) token
2. Go to 'Settings'
3. Change network to 'testnet'
4. Go to 'Wallets'
5. Pay attention to wallets

**Comment by DmRos** [comment]
Amendment

Refreshing balance in Staking causes "UI Rendering Error..." (Chrome, Firefox)

Prerequisites:
Testnet, Mainnet

Steps to reproduce:

1. Staking > Delegate > select any pool.
2. Click on button to refresh $ Balance at the upper left corner. >
3. OR click drop-down list, change account (also goes with refreshing balance automatically)

Actual result:  after refreshing wallet app crashes with "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer" alert.
Expected result: Refreshed balance.

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Firefox 85.0 (32-bit)

**Comment by Corresponsible** [comment]
amendment filed
