### ISSUE TITLE
"Transaction in progress" warning message skip

### ISSUE THREAD

**Issue by ArnerPan** [velas/JsWallet#69]
Summary
Possible to skip warning message on   "transaction in progress " page when operation is not comlpeted yet
 
Video
[RECORD](https://youtu.be/4CmU_s2koHU)

**Steps to reproduce:**
1. Go to 'Wallets'
2. Choose Velas wallet
3. Click "send"
4. Copy VLX address wallet "from:"
5. Past VLX address to "To"
6. Set any amount but less than on balance
7. Choose Transaction Fee "Custom"
8. Set value of Transaction Fee less than 0.000000011 or just 0.000000000
9. Click "Send"
10. Click "Confirm"
11. On the next page try to click any button from the left bar  ("Wallets"  or "Settings"  ...etc) instead  of clicking  "home" button in the center

**Expected result**
User should recieve a warning message about uncompleted operations  on account 

**Actual result**
Message being skipped  user  leaves from "transaction in progress "page  wihtout any warnings if  transaction is  still not completed yet 

Environment:
Build [0.13.21]
Device [laptop y530]
OS [Windows 10 x64]
Browser [Chrome]
Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Again, too small fees is to be used on user's risk, mostly people in crypto are aware they shouldn't use fees close or equal to zero
