### ISSUE TITLE
When you go to the Support tab, the localization setting is not saved

### ISSUE THREAD

**Issue by hob83** [velas/JsWallet#70]
**Summary**
When you go to the Support tab, the localization setting is not saved

**Screenshot**

![velas](https://user-images.githubusercontent.com/74620381/106497400-ac2f1100-64c6-11eb-8708-9fb113ccd8f6.jpg)

**Steps to reproduce:**
1. Go to 'Settings'
2. Make sure English is enabled
3. Click on 'Support'
4. Pay attention to 'Support' localization language 

**Expected result**
'Support' localization language is the same as the language selected in Velas.

**Actual result**
The 'Support' localization language is Russian, and the language selected in Velas is English..

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Not a Wallet site, oos
