### ISSUE TITLE
Staker pool values not changed after sending tokens from wallet

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#71]
**Summary**
Staker pool values not changed after sending tokens from wallet

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106503409-3e86e300-64ce-11eb-9b87-49f08475037a.png)

**Steps to reproduce:**
1. Go to 'Staking' --> 'Delegate'
2. Copy wallet address one of stakers (where you are not staker)
3. Go to 'Wallets'
4. Click on 'Velas' token
5. Click on [SEND] button
6. Enter valid staker wallet adress
7. Enter '10000' into 'Amount' field
8. Click on [SEND] button
9. Go to 'Staking' --> 'Delegate'
10. Pay attention to 'Total stake', 'My stake' and 'Stakers' from staker to which you are sent the tokens

**Expected result**
Staker pool values changed after sending tokens from wallet. Or after step '6' dysplayed error message 'use "Staking" -->"Delegete" for sending to this adress'

**Actual result**
Staker pool values not changed after sending tokens from wallet

**Additional context, details, and ideas**
User can lost tokens

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by DmRos** [comment]
they seem to appear sometimes lot later
