### ISSUE TITLE
By scrolling Account Index new account is created but can't see it in list

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#73]
Prerequisites:
Testnet, Accounts created - 6

Steps to reproduce:
1. Settings > scroll Account Index to a random, bigger than actually created (8)
2.  Wallets > can see: 'Account 8' at the top of "switch-account" list and new account number created 
3. Copy new number > Testnet Telegram bot will top it up and sending/receiving transactions possible 
4. Switch to a created by "Create Account" account > 'Account 8' not on the list.

To see 'Account 8' again:
1. settings > scroll to 'Account Index 8' > Wallets
 
Expected result
Accounts are created by dedicated button only and (or being created by any means) - visible in list.

Actual result
Account created but not visible in "switch-account" list
![New Bitmap Image5](https://user-images.githubusercontent.com/73913130/106509915-e1435f80-64d6-11eb-96fd-723428f95210.jpg)

Pay attention - Account Index very slow scrolling.

Environment:

Build [0.13.21]
OS [Windows 7 x64]
Browser [Chrome]
Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Right now ths is how the feature works, not a bug
