### ISSUE TITLE
error message "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer" 

### ISSUE THREAD

**Issue by Anthrax941** [velas/JsWallet#76]
**Summary**
When changing wallet or refresh balance in the "Delegate>Select pool" window, an error message appears "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer"

**Screenshot**
![Безымянный1](https://user-images.githubusercontent.com/73966415/106545293-ce01b580-6511-11eb-979c-f75045d01b65.png)
![ППпппппп](https://user-images.githubusercontent.com/73966415/106545070-5d5a9900-6511-11eb-8ed8-aa198133e84d.png)

**Steps to reproduce:**
1. Go to Staking > Delegate>Select pool
   1.1 Click drop dawn list [Account]
   1.2 Сhoose another wallet
2. Go to Staking > Delegate>Select pool
   2.1 Refresh balance

**Expected result**
1. Exit to the menu "Delegate"
2. Balance updated

**Actual result**
Error message "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer"  

**Environment:**
- Build [0.13.21]
 - Windows 10 x64
 - Chrome
 - Version [88.0.4324.104]

**Comment by DmRos** [comment]
Amendment

Refreshing balance in Staking causes "UI Rendering Error..." (Chrome, Firefox)

Prerequisites:
Testnet, Mainnet

Steps to reproduce:

1. Staking > Delegate > select any pool.
2. Click on button to refresh $ Balance at the upper left corner.
3. OR click drop-down list, change account (also goes with refreshing balance automatically)

Actual result: app crash with "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer"
Expected result: Refreshed balance, stable app.

Image3

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Firefox 85.0 (32-bit)

**Comment by Corresponsible** [comment]
amendment filed
