### ISSUE TITLE
when withdrawing funds from the pool, in the transaction history the amount = 0,000

### ISSUE THREAD

**Issue by Anthrax941** [velas/JsWallet#77]
**Screenshot**
![Безымянный](https://user-images.githubusercontent.com/73966415/106551853-ce547d80-651e-11eb-91c5-9d179c8db6ea.png)
![Безымянный2](https://user-images.githubusercontent.com/73966415/106551866-d2809b00-651e-11eb-9f32-5b1a11a009cf.png)

**Steps to reproduce:**
1. Have a stake of pool
2. Go to Staking > Delegate
3. Choose pool where you have a stake
4. Withdraw VLX

**Expected result**
In transaction history transfer amount = amount withdrawn

**Actual result**
In transaction history transfer amount = 0,0000

**Environment:**
 - Build [0.13.21]
 - Windows 10 x64
 - Chrome
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
You should have 2 transactions in history: 1st with 0000 2nd with your amount returned
Is this the case?
If yes - first is contract execution trace, and can not go to history, 2nd is incoming funds transaction, and it should also show in history

**Comment by Anthrax941** [comment]
the 2nd transaction appears after a few minutes
