### ISSUE TITLE
Wrong description for account index option (The range is adjustable to 0-2 147 483 647, should be 999 999 999)

### ISSUE THREAD

**Issue by rodinant** [velas/JsWallet#78]
**Summary**
Unable to create account index greater than 999 999 999. But in the description we see: The range is adjustable to 0-2 147 483 647

**Screenshot**
![issue_1](https://user-images.githubusercontent.com/73893397/106564298-bc320980-6535-11eb-8678-c71a4933b7a9.jpg)

**Steps to reproduce:**
1.	Go to 'Settings' --> 'SWITCH ACCOUNT INDEX'. (In the description we see: The range is adjustable to 0-2 147 483 647)
2.	Enter the number 999 999 999 in the "Account index" field
3.	When trying to increase the index by clicking on ">", we see an Alert; _999999999 is the highest account index_

If you _set any account index greater than 999 999 999_ (for example 1000000000) in the input field _manually_, the index will switch to 1 and _there will be no alert_

**Expected result**
The account index can be set more than 999 999 999 (but not more than 2 147 483 647)

**Actual result**
Unable to create account index greater than 999 999 999

**Environment:**
•	Testnet or Mainnet
•	Build [0.13.21]
•	OS [Windows 7 x64]
•	Browser [Chrome]
•	Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
This is indeed the case, we didn't change the description after the feature has changed, unfortunately we're not working with texts and translations now, so this will be closed, sorry
