### ISSUE TITLE
UI: Long custom Account Name overlaps EPOCH span/icon

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#79]
Steps to reproduce:

1. Change an Account Name to string longer than 11 
2. Staking > Node/Delegate/Statistics

Expected result:
Spans accommodate to be visible

Actual result:
Long custom Account Name overlaps EPOCH span/icon.

![New Bitmap Image3](https://user-images.githubusercontent.com/73913130/106567487-952a0680-653a-11eb-988d-d143f34d1b88.jpg)

Environment:

Build [0.13.21]
OS [Windows 7 x64]
Laptop 17'' //  Dell 23'' Monitors
Browser(s): Chrome 88.0.4324.104 // Firefox 85.0 (32-bit)

**Comment by Corresponsible** [comment]
This partially goes under https://github.com/velas/JsWallet/issues/38
Though yes, it is a bug, I will close it but give you points for it
