### ISSUE TITLE
After clearing browser cache some previously open Velas tabs loged in and making transactions possible

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#80]
After clearing browser cache other than WALLETS tabs still logged in and making transactions possible

Steps to reproduce:

Testnet, vlx.
1. Few Velas Wallet concurrent tabs opened: Wallets, Delegate, Settings.
2. chrome://settings/clearBrowserData > Advanced, All time > Checked everything except Browsing and Download history > Clear. 
3. Switch to opened Wallets tabs > tabs require Seed Phrase.
4. Switch to opened Delegate, Settings or Transactions tabs > able to navigate and make transactions.

![clear](https://user-images.githubusercontent.com/73913130/106589522-c4e60800-6554-11eb-9fc3-a4fea817844c.jpg)

Expected result: all previously opened tabs after clearing browsing data are logged off and require Seed Phrase to operate.

Actual result: other than WALLETS tabs still logged in and making transactions possible.

Other side effects:
- regarding **tab from step 4**. : all but default first three accounts names are invisible in Wallets drop-down after step 2. Still possible to access via 'Settings > Account index' but names customization lost. 
Environment:

Build [0.13.21]
OS [Windows 7 x64]
Laptop 17'' // Dell 23'' Monitors
Browser(s): Chrome 88.0.4324.104

**Comment by Corresponsible** [comment]
what happens with step 4 if you refresh tabs or reopen browser after step 2?
