### ISSUE TITLE
Hovering over circle around coins displays the values of the pending transaction

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#81]
**Summary**
Hovering over circle around coins displays the values of the pending transaction

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106603342-d6d0a680-6566-11eb-8eab-a8cb738702c4.png)

**Steps to reproduce:**
1. Start receiving coin transactions
2. Go to wallet with this coin
3. Hover over values circle with info, when transaction status 'Created'

**Expected result**
Hovering over circle around coins not displays the values of the pending transaction

**Actual result**
Hovering over circle around coins displays the values of the pending transaction

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Not to be fixed, consider not a bug
