### ISSUE TITLE
Litecoin can't be sent 

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#82]
**Summary**
Litecoin can't be sent, only received from outside

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106606939-5f514600-656b-11eb-83b6-ed38e5f67118.png)

**Steps to reproduce:**
1. Click on 'Litecoin' wallet
2. Enter valid data into fields
3. Click on [SEND]

**Expected result**
Transaction is created, coins are sent

**Actual result**
Litecoin can't be sent after sending with entering valid data, error message is shown

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Can you proceed sending LTC after previous transaction has been approved?
Does it only happen when you send to the same address you're sending from?

**Comment by PrivetQA** [comment]
@Corresponsible LTC can't be sent with any valid data, always shows error message

**Comment by Corresponsible** [comment]
Litecoin can't be sent after sending - means you sent before and all further transactions don't work (then specify in steps), or you can't actually send at all? (clarify title)
