### ISSUE TITLE
Сan't perform any transactions after cancelling LTC transaction

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#83]
**Summary**
[SEND] button doesn't work, impossible to make a transaction, [SEND] button became [...]

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106608446-139f9c00-656d-11eb-99e3-226207ce4081.png)

**Steps to reproduce:**
1. Click on 'Litecoin'
2. Enter invalid adress into 'To'
3. Enter valid 'Amount'
4. Click on [SEND]
5. Click on [CANCEL]
6. Try to send with any wallets in any network

**Expected result**
[SEND] button work correctly

**Actual result**
[SEND] button doesn't work, impossible to make a transaction, [SEND] button became [...]

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Update title, see https://github.com/velas/test-us/issues/10#issuecomment-772481297
