### ISSUE TITLE
The 'Help' button overlaps the Language Bar

### ISSUE THREAD

**Issue by olan-d** [velas/JsWallet#86]
**Summary**
The 'Help' button  overlaps the Language Bar in the Customer Support page.

**Screenshot**
![InkedVelas bug](https://user-images.githubusercontent.com/73910112/106613895-61b79e00-6573-11eb-812a-bc67f534819c.jpg)

**Steps to reproduce:**
1. Go to 'Support'
2. Pay attention to 'Language Bar' (when the page scale is 100% or full screen)

**Expected result**
The Language Bar is always visible.

**Actual result**
The Language Bar is not visible. It is obscured by the 'Help' button.

**Environment:**
 - Device [Laptop HP 15.6'']
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
This is not a Wallet site, it's a different site, oos
