### ISSUE TITLE
'Calc Fee Error' message after entering 'Amount' with invalid Ethereum adress

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#87]
**Summary**
'Calc Fee Error' message after entering 'Amount' with invalid Ethereum adress

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106618539-3daa8b80-6578-11eb-8286-0f0091ba462e.png)

**Steps to reproduce:**
1. Click on 'Ethereum' wallet
2. Click on 'Send'
3. Enter invalid adress
4. Enter valid amount

**Expected result**
No error message

**Actual result**
'Calc Fee Error' message after entering 'Amount' with invalid Ethereum adress

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
As devs explained: ETH cannot calculate fee, because address is incorrect, thus the message is legit. Might be not obvious to the user, but won't fix, unfortunately
