### ISSUE TITLE
After new login  from other Browser only three default acconts visible in list. Custom Account names lost.

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#88]
After new log in from other Browser only three default accounts visible in Wallets drop-down list. User-created accounts are accessible via Settings > Account Index only. Custom Account names changed to index names. 

Prerequisites:
Testnet

Steps to reproduce:

1. Create few more VLX accounts, give custom names.
2. (Switch to other Windows User) launch a different browser or clear browsing data/cache in the browser used with Velas before.
3. Login with Seed Phrase.
4. Only three default accounts visible, custom names are lost.
5. User-created accounts only accessible via Settings > Account Index

Expected result: all created accounts visible in list with their customized names.

Actual result: only three default accounts visible, custom names are changed to basic index names.

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): 1st -Chrome 88.0.4324.104 // 2nd - Edge 88.0.705.56 (Official build) (64-bit)

**Comment by Corresponsible** [comment]
Wallet stores names in cache as there is no server to store them, so this is how the feature works, although it might seem illogical
