### ISSUE TITLE
Refreshing balance in Staking causes "UI Rendering Error..." (Chrome, Firefox)

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#91]
Prerequisites:
Testnet, Mainnet

Steps to reproduce:

1. Staking > Delegate > select any pool.
2. Click on button to refresh $ Balance at the upper left corner. > 
3. OR click drop-down list, change account (also goes with refreshing balance automatically)

Actual result: "UI Rendering Error: Cannot read property 'address' of null. Please contract to wallet developer"
Expected result: Refreshed balance, stable tab.

![New Bitmap Image3](https://user-images.githubusercontent.com/73913130/106631937-e8757680-6585-11eb-9809-ef8d11b4a75f.jpg)

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Firefox 85.0 (32-bit)

**Comment by Corresponsible** [comment]
https://github.com/velas/JsWallet/issues/76 dup

**Comment by DmRos** [comment]
this one more broad and points to the real cause. but never mind :)

**Comment by Corresponsible** [comment]
I agree, but it's not a new bug, for all refinements you can add an amendment is stated in the rules, go ahead and file your amendment ;)

**Comment by DmRos** [comment]
done
