### ISSUE TITLE
English parts on the page of transfer in the russian version

### ISSUE THREAD

**Issue by SvetlanaPonomarenko** [velas/JsWallet#92]
**Summary**
English parts on the page of transfer in the russian version

**Screenshot**
![image](https://user-images.githubusercontent.com/74476480/106668965-9ea38500-65b3-11eb-91a0-2c8e4cc36872.png)

**Steps to reproduce:**
1. Go to wallets
2. Click send

**Expected result**
Title "Transaction fee" in russian
Title of field selected account in russian
Message "Not Enough Funds" in russian

**Actual result**
Title "Transaction fee" in english
Title of field selected account in english
Message "Not Enough Funds" in english

**Environment:**
 - OS [Windows 10 Home x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
As stated in rules, translation and localization is out of scope
