### ISSUE TITLE
Unable to transfer currency from VLX2ETH

### ISSUE THREAD

**Issue by IgDiElw** [velas/JsWallet#95]
**Summary**
VLX2ETH currency conversion not working

**Screenshot**
![Send](https://user-images.githubusercontent.com/73854750/106681830-5ba4da00-65d2-11eb-9fcc-35a39be94a46.PNG)
![Send2](https://user-images.githubusercontent.com/73854750/106681835-5e073400-65d2-11eb-8dae-204a4592c332.PNG)
![result](https://user-images.githubusercontent.com/73854750/106681839-5fd0f780-65d2-11eb-99d3-553f198e1558.PNG)

**Steps to reproduce:**
1. Have currency on your wallet
2. Copy Ethereum wallet address
3. Click on 'SEND' near Velas wallet
4. Paste the Ethereum wallet address into 'To' field 
5. Enter in the 'Amount' field in the range from 0 to the maximum number of tokens on the account.
6. Click on 'SEND'
7. Click on 'Confirm'

**Expected result**
Ethereum wallet replenishment

**Actual result**
Sending currency to your own VLX address

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browsers [Chrome, Firefox]
 - Version [88.0.4324.146, 85.0]

**Comment by Corresponsible** [comment]
This is not an exchange site, there's is no conversion intended

**Comment by Corresponsible** [comment]
Clarification: there does exist address convertion, but to convert coins from one to another you'd need an exchange
