### ISSUE TITLE
Double transactions in history after sending Ethereum to the same address sent from

### ISSUE THREAD

**Issue by PrivetQA** [velas/JsWallet#99]
**Summary**
Double transactions in history after sending Ethereum to the same address sent from

**Screenshot**
![image](https://user-images.githubusercontent.com/71498900/106747943-398c7580-662d-11eb-8ac6-8abe476dfa82.png)

**Steps to reproduce:**
1. Click on 'Ethereum' wallet
2. Copy Ethereum address
3. Click on 'Send'
4. Paste Ethereum address into 'To' field
5. Enter valid values into 'Amount'
6. Click on [SEND]
7. Click on [CONFIRM]
8. Click on [HOME]
9. Wait for transaction status 'Confirmed'
10. Click on [DETAILS] icon
11. Pay attention to transactions history

**Expected result**
Created 1 transaction in 'TRANSACTIONS' history after sending Ethereum to himself

**Actual result**
Created double transactions in history after sending Ethereum to himself

**Additional information**
This bug creates problems with displaying transactions history and history after changing account index
![image](https://user-images.githubusercontent.com/71498900/106764597-9a717900-6640-11eb-9804-dde60dbeed98.png)
![image](https://user-images.githubusercontent.com/71498900/106764653-a9f0c200-6640-11eb-98c0-eae14e58b9bc.png)
https://youtu.be/5nphcIOccsQ

**Environment:**
 - Build [0.13.21]
 - OS [Windows 10 x64]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by Corresponsible** [comment]
Can you compress the three to one bug with specifying repercussions in additional info?
